SPEAKERDECK = 'SPEAKERDECK'
SLIDESHARE = 'SLIDESHARE'
YOUTUBE = 'YOUTUBE'
VIMEO = 'VIMEO'

SLIDE_TYPE_CHOICES = (
    (SPEAKERDECK, 'SpeakerDeck'),
    (SLIDESHARE, 'SlideShare'),
)

VIDEO_TYPE_CHOICES = (
    (YOUTUBE, 'Youtube'),
    (VIMEO, 'Vimeo'),
)

